/*
* TokenType.h
*/

#ifndef TOKENTYPE_H_
#define TOKENTYPE_H_

enum TType {
	TOKEN_INTEGER = 0,
	TOKEN_IDENTIFIER,
	TOKEN_PLUS,
	TOKEN_MINUS,
	TOKEN_COLON,
	TOKEN_SMALLER,
	TOKEN_GREATER,
	TOKEN_EQUALS,
	TOKEN_ASSIGN,
	TOKEN_ASSIGN2,
	TOKEN_NOT,
	TOKEN_AND,
	TOKEN_SEMICOLON,
	TOKEN_STAR,
	TOKEN_BRACKETS0_OPEN,
	TOKEN_BRACKETS0_CLOSE,
	TOKEN_BRACKETS1_OPEN,
	TOKEN_BRACKETS1_CLOSE,
	TOKEN_BRACKETS2_OPEN,
	TOKEN_BRACKETS2_CLOSE,
	TOKEN_IF,
	TOKEN_INT,
	TOKEN_ELSE,
	TOKEN_READ,
	TOKEN_WHILE,
	TOKEN_WRITE,
	TOKEN_UNKNOWN,
	TOKEN_EOF
};

#endif /* TOKENTYPE_H_ */
